[package]
name = "progenitor-macro"
version = "0.1.1"
edition = "2018"
license = "MPL-2.0"
repository = "https://github.com/oxidecomputer/progenitor.git"
description = "An OpenAPI client generator - macros"

[dependencies]
openapiv3 = "1.0.0"
proc-macro2 = "1.0"
progenitor-impl = { version = "0.1.1", path = "../progenitor-impl" }
quote = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_tokenstream = "0.1.3"
syn = "1.0"

[lib]
proc-macro = true
