[package]
name = "progenitor-macro"
version = "0.2.1-dev"
edition = "2021"
license = "MPL-2.0"
description = "An OpenAPI client generator - macros"
repository = "https://github.com/oxidecomputer/progenitor.git"
readme = "../README.md"

[lib]
proc-macro = true

[dependencies]
openapiv3 = "1.0.0"
proc-macro2 = "1.0"
progenitor-impl = { version = "0.2.1-dev", path = "../progenitor-impl" }
quote = "1.0"
schemars = "0.8.11"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_tokenstream = "0.1.4"
syn = "1.0"
